jwt:
  secret: assignmentkafka
spring:
  kafka:
    producer:
      bootstrap-servers: 3.82.60.32:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/kafkarecords
    username: publisher
    password: password45
  jpa:
    hibernate:
      ddl-auto: update